server:
  port: 9527
  servlet:
    context-path: /api

spring:
  application:
    name: yanManus
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY:}
      chat:
        options:
          model: qwen-plus
    mcp:
      client:
        sse:
          connections:
            stdio: true
            servers-configuration: classpath:mcp-servers.json

serpapi:
  api-key: ${SERPAPI_API_KEY:}


